
smart_module.news_admin:
    path: /
    defaults:
        _controller: SimpleNewsModuleBundle:NewsAdmin:index

smart_module.news_admin.create:
    path: /create/
    defaults:
        _controller: SimpleNewsModuleBundle:NewsAdmin:create

smart_module.news_admin.edit:
    path: /{id}/edit
    defaults:
        _controller: SimpleNewsModuleBundle:NewsAdmin:edit
    requirements:
        id: \d+
